networks:
  administrative-api:
    external: true
    name: administrative-api

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    env_file: .env
    environment:
      - SERVICES=lambda,dynamodb,apigateway,iam
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=administrative-api
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".localstack:/var/lib/localstack"
    networks:
      - administrative-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 15
